name: CalBump
description: Bumps a version file based on the current date & time
author: Sensanaty

outputs:
  previous-version:
    description: The previous version found in the VERSION file
  new-version:
    description: The new version of the project

runs:
  using: node20
  main: dist/index.js

branding:
  color: "green"
  icon: "calendar"
