name: Testing Action Run

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  test-action:
    permissions:
      contents: write

    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get-tag
        run: |
          echo "TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          tag: ${{ env.TAG }}

      - name: Create annotated tag
        id: tag
        env:
          OLD: ${{ steps.test-action.outputs.old }}
          NEW: ${{ steps.test-action.outputs.new }}
          USER: ${{ github.actor }}
          EMAIL: ${{ github.event.pusher.email }}
          LAST_COMMIT: ${{ github.event.commits[0].message }}

        run: |
          echo "Bumping from ${OLD} to ${NEW}"
          git config --local user.name "${USER}"
          git config --local user.email "<${EMAIL}>"
          git tag -a $NEW -m "${LAST_COMMIT}"
          git push origin $NEW
