name: Testing Action Run

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Merge version bump
        id: merge
        env:
          OLD_VERSION: ${{ steps.test-action.outputs.previous-version }}
          NEW_VERSION: ${{ steps.test-action.outputs.new-version }}
        run: |
          git config --local user.name "Github Action Runner"
          git config --local user.email "<>"
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Version bumped from ${OLD_VERSION} to ${NEW_VERSION}"
