name: Testing Action Run

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Output local action outputs
        id: outputs
        env:
          OLD_VERSION: ${{ steps.test-action.outputs.previous-version }}
          NEW_VERSION: ${{ steps.test-action.outputs.new-version }}
        run: echo "Previous is $OLD_VERSION, New is $NEW_VERSION"
